void cal_con(int y1, int m1, int d1, int y2, int m2, int d2, int indx);
void sctomc(int year, int month, int day, FILE *iw, int *yy, int *mm, int *dd, char *mganji);
void mctosc(int year, int month, int day, FILE *iw, int *yys, int *mms, int *dds);
int  dayofmon(int year, int month);
int  fundate(int year, int month, int day);
int  fundgg(int year, int month, int day);
int  funmgg(int year, int month);
int  funygg(int year);
void gethname(char *hnamegg[]);
void towang(int year, double jd[]);
void hansig(int year, FILE *iw, int *month, int *day);
void sambok(int year, FILE *iw, int month[], int day[]);
int  dayofsun(int year);
void getmymm(int no24[], int nnn, int year, int month, int *myear, int *mmon);
void ss24(FILE *iw1, FILE *iw2, int y[], int m[], double d[], int eflag, char hnamegg[]);
