int NO_OF_AXIS;
//========================================================
int  TELESCOPE_TYPE;
enum {_ALT_AZI, _RA_DEC};

int TELESCOPE_MODE;
enum {TEL_MODE_STOP, TEL_MODE_SLEW, TEL_MODE_TRACK, TEL_MODE_PARK, TEL_MODE_INIT};

int SLEW_MODE[3];
enum {_SLEW_MODE_ON,_SLEW_MODE_OFF};

int  GUIDE_MODE;
enum {GUIDE_MODE_OFF,GUIDE_MODE_HP,GUIDE_MODE_MOUSE,GUIDE_MODE_ST4};

d_m_s   SITE_LONGI,SITE_LATI;
double  SITE_HEIGHT;

double  DUT1_SEC,DUT1_DAY;

double  MOUNT_HA[20], MOUNT_DEC[20],ENC_TO_STEP[2];
double  PSI_FACTOR; // PSI_COUNT = PSI_DEGREE * PSI_FACTOR
long    INIT_COUNT[2], HOME_COUNT[2];
double  OFFSET_HA_COUNT,OFFSET_DEC_COUNT;
double  OFFSET_HA_ARCMINUTE,OFFSET_DEC_ARCMINUTE;
int     ENCODER_MODE;
double  SERVO_UPDATE_SEC;

double  MEAN_TRACKING_FREQ[2];
double  PARK_FREQ [2], PARK_SPEED [2],
        INIT_FREQ [2], INIT_SPEED [2],
        GUIDE_FREQ[2], GUIDE_SPEED[2],
        GSET_FREQ [2], GSET_SPEED [2],
        SLEW_FREQ [2], SLEW_SPEED [2];
switch_status SWSTATUS[2];
ramp_data VPROFILE[2];
home_para HOMEP[2];

char   STAR_STRING[150];
double MAX_ERROR_RA_ARCSEC, MAX_ERROR_DEC_ARCSEC;
double JDUTC_0;           

int   DER_TRACKING;
enum {DER_TRACKING_ON,DER_TRACKING_OFF};

int SW_LIMIT;

h_m_s  TARGET_RA_2000 ,CURRENT_RA ;
d_m_s  TARGET_DEC_2000,CURRENT_DEC;
char   TARGET_NAME[100];

h_m_s CURRENT_LAST;
int LINKDOME;

double HALIMITMAX,HALIMITMIN; 
int USEPRELOAD;

int NODENO;
double ENCTOSTEP_RA[4],ENCTOSTEP_DE[4];
